
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package ucu;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PIPE = 20;
  public static final int LONG = 7;
  public static final int RCLASP = 14;
  public static final int LCLASP = 13;
  public static final int TRUE = 5;
  public static final int LBRACKET = 15;
  public static final int COLON = 12;
  public static final int ID = 19;
  public static final int HEXINTEGER = 8;
  public static final int RBRACKET = 16;
  public static final int HEXLONG = 6;
  public static final int STRING = 2;
  public static final int FLOAT = 10;
  public static final int EOF = 0;
  public static final int LPARENTHESIS = 17;
  public static final int RPARENTHESIS = 18;
  public static final int FALSE = 4;
  public static final int error = 1;
  public static final int INTEGER = 9;
  public static final int TP = 21;
  public static final int NULL = 3;
  public static final int DOUBLE = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STRING",
  "NULL",
  "FALSE",
  "TRUE",
  "HEXLONG",
  "LONG",
  "HEXINTEGER",
  "INTEGER",
  "FLOAT",
  "DOUBLE",
  "COLON",
  "LCLASP",
  "RCLASP",
  "LBRACKET",
  "RBRACKET",
  "LPARENTHESIS",
  "RPARENTHESIS",
  "ID",
  "PIPE",
  "TP"
  };
}

